# This formula is auto-generated by the CI pipeline via gen_brew_formula.sh.
# To regenerate: trigger the homebrew-package workflow or run:
#   ./vendor/script-helpers/scripts/gen_brew_formula.sh \
#     --name image-view \
#     --desc "Render images directly in your terminal" \
#     --homepage "https://github.com/nikolareljin/image-view" \
#     --tarball dist/image-view-<version>.tar.gz \
#     --url "https://github.com/nikolareljin/image-view/archive/refs/tags/<version>.tar.gz"

class ImageView < Formula
  desc "Render images directly in your terminal"
  homepage "https://github.com/nikolareljin/image-view"
  # url and sha256 are filled in by gen_brew_formula.sh at release time
  url "https://github.com/nikolareljin/image-view/archive/refs/tags/0.6.2.tar.gz"
  sha256 "PLACEHOLDER_SHA256_UPDATED_BY_CI"
  version "0.6.2"
  license "MIT"

  depends_on "rust" => :build

  def install
    system "cargo", "install", "--locked", "--root", prefix, "--path", "."
  end

  test do
    assert_match "image-view", shell_output("#{bin}/image-view --help")
  end
end
