name: Release

on:
  push:
    tags:
      - 'v*.*.*'
      - '*.*.*'
      - 'v*.*.*-rc*'
      - '*.*.*-rc*'
      - 'v*.*.*-RC*'
      - '*.*.*-RC*'
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Tag to build and release (e.g. 0.7.1)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  release:
    uses: nikolareljin/ci-helpers/.github/workflows/rust-release.yml@production
    with:
      bin_name: "image-view"
      release_tag: ${{ github.event.inputs.release_tag || github.ref_name }}
